version: '3.1'
services:
  nest:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - nest-mongodb

  nest-mongodb:
    image: mongo
    ports:
      - "27017:27017"
