version: '3.9'
services:
  nginx:
    container_name: jianshu-web
    image: jianshu-demo-web:latest
    ports:
      - "8088:8088"
      - "8080:8080"
      - "80:80"
      - "443:443"
    depends_on:
      - nest
    networks:
      - jianshu-network

  nest:
    container_name: jianshu-server
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URL=nest-mongodb
      - NODE_ENV=development
    ports:
      - "3000:3000"
    depends_on:
      - nest-mongodb
    networks:
      - jianshu-network

  nest-mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - jianshu-network
networks:
  jianshu-network:
    driver: bridge
